version: '3.8'
services:
  web:
    container_name: web
    image: nginx:stable-alpine
    volumes:
      - "./:/app"
      - "./docker/nginx/www.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    ports:
      - "8000:80"
    networks:
      - symfony
  php:
    container_name: php
    build:
      context: docker/php-fpm
    volumes:
      - "./:/app"
      - "./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    networks:
      - symfony
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - symfony

networks:
  symfony:
